title: Gekang
homeTitle: NICK KANG
email: hkang72@wisc.edu
description: I have been focusing on building up my skill sets with Data Programming, Data Analysis, Economic Forecasting and Machine learning. These skill sets help me make the dive into the data world and make my attempt to analyze different interesting topics. I enjoy the process of preparing data, manipulating data and creating plots in order to discover trends and patterns or pose and answer questions with data-driven insights. 
author: Nick Kang
baseurl: ""
url: "https://honggekang.github.io"

# Social Profiles
twitter_username:
github_username:
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
